cmake_minimum_required(VERSION 3.20)
project(miltech_cpp CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

enable_testing()

add_subdirectory(homework_04)
add_subdirectory(homework_05)
add_subdirectory(homework_06)
add_subdirectory(homework_07)
add_subdirectory(homework_08)
add_subdirectory(homework_09)
add_subdirectory(homework_10)
add_subdirectory(homework_11)
add_subdirectory(homework_15)
add_subdirectory(homework_16)
add_subdirectory(homework_17)
